version: 2
before:
  hooks:
    - go mod tidy
builds:
  - no_unique_dist_dir: false
    ldflags:
      - -X {{ .ModulePath }}/internal.Version={{.Version}} -X {{ .ModulePath }}/internal.Commit={{.Commit}} -X {{ .ModulePath }}/internal.Date={{.CommitDate}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      #- windows
      - darwin
archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{- .Os }}_{{ .Arch }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      formats:
        - zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
